# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseProject:-

    pod 'Alamofire'
    pod 'Toast-Swift'
    pod 'IQKeyboardManagerSwift'
    pod 'AlamofireNetworkActivityLogger'
    pod 'Kingfisher'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RealmSwift'
    pod 'KeychainSwift'

#    post_install do |installer|
#       installer.pods_project.targets.each do |target|
#           target.build_configurations.each do |config|
#               config.build_settings['SWIFT_VERSION'] = '4.2'
#           end
#       end
#   end
end
